@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Пользователь" as User
participant "Мобильное приложение" as MobileApp
participant "Сервис кабинета клиента" as ClientService
participant "Сервис пользователей" as UserService
participant "Сервис ядро" as CoreService

User -> MobileApp
activate MobileApp

    MobileApp -> ClientService
    activate ClientService

alt #lightgreen Успешная регистрация
        ClientService -> UserService: POST /register
        activate UserService
        return TokenDto

        MobileApp <-- ClientService: HTTP 200:\n возвращаем JWT
        User <-- MobileApp: Экран кабинета
else #pink
        ClientService -> UserService: POST /register
        activate UserService
        return HTTP 4xx
    return HTTP 4xx
return Экран ошибки
end

@enduml