@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Пользователь" as User
participant "Мобильное приложение" as MobileApp
participant "Сервис кабинета клиента" as ClientService
participant "Сервис ядро" as CoreService
participant "Сервис пользователей" as UserService

User -> MobileApp
activate MobileApp

    MobileApp -> ClientService
    activate ClientService

        note right ClientService
        {userId} получаем из токена
        end note

        note right ClientService
        Прокидываем Bearer токен в header Authorization
        end note

        note right ClientService
        Передаем негативное изменение баланса
        end note

        ClientService -> CoreService: POST /users/{userId}/bills/{billId}/transactions
        activate CoreService

            CoreService -> UserService: GET /users/me
            activate UserService
            return HTTP 200: информация о пользователе
        return HTTP 200
    return HTTP 200
return Экран успеха

@enduml