version: '3.3'

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:8080"
    environment:
      ConnectionStrings__DefaultConnection: Server=gatewayEmployeeDB;Port=5432;Database=gatewayEmployeeDatabase;Username=postgres;Password=asd123
      ASPNETCORE_ENVIRONMENT: Staging
      RABBITMQ_HOST: 194.147.90.192
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: huba
      RABBITMQ_PASSWORD: ELeuAbAUm9Lp0ti8
      RABBITMQ_VHOST: huba
    depends_on:
      - local-database
    networks:
      - db-network

  local-database:
    image: postgres:latest
    container_name: "gatewayEmployeeDB"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gatewayEmployeeDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asd123
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
