# Конфигурация CI/CD для репозиториев микросервисов проекта "Цифровой след".
# Специфичные настройки под конкретный микросервис вынесены в раздел "variables".

include:
  - '/.infra/gitlab-ci-templates/.java-ci.yml'
  - '/.infra/gitlab-ci-templates/.docker-ci.yml'

variables:
  STAGING_FOLDER: /opt/hubabank

stages:
  - build
  - test
  - image
  - deploy

core:build:
  extends: .build_java_gradle
  needs: []
  variables:
    PROJECT_DIR: core

core:test:
  extends: .test_java_gradle_with_testcontainers
  needs:
    - core:build
  variables:
    PROJECT_DIR: core

core:image:
  extends: .build_docker_image
  needs: []
#    - core:test
  variables:
    DOCKERFILE: .infra/dockerfiles/java/Dockerfile
    IMAGE: hubabank/core
    PROJECT_DIR: core

user:build:
  extends: .build_java_gradle
  needs: []
  variables:
    PROJECT_DIR: java/users

user:test:
  extends: .test_java_gradle
  needs:
    - user:build
  variables:
    PROJECT_DIR: java/users
