# Конфигурация CI/CD для репозиториев микросервисов проекта "Цифровой след".
# Специфичные настройки под конкретный микросервис вынесены в раздел "variables".

include:
  - '/.gitlab-ci-templates/.java-ci.yml'

variables:
  STAGING_FOLDER: /opt/hubabank

stages:
  - build
  - test

core:build:
  extends: .build_java_gradle
  needs: []
  variables:
    PROJECT_DIR: core

core:test:
  extends: .test_java_gradle_with_testcontainers
  needs:
    - build:core
  variables:
    PROJECT_DIR: core

user:build:
  extends: .build_java_gradle
  needs: []
  variables:
    PROJECT_DIR: java/users

user:test:
  extends: .test_java_gradle
  needs:
    - build:user
  variables:
    PROJECT_DIR: java/users
