# Конфигурация CI/CD для репозиториев микросервисов проекта "Цифровой след".
# Специфичные настройки под конкретный микросервис вынесены в раздел "variables".

include:
  - '/.gitlab-ci-templates/.java-ci.yml'

variables:
  STAGING_FOLDER: /opt/hubabank

stages:
  - build
  - test

build:core:
  extends: .build_java_gradle
  dependencies: []
  variables:
    PROJECT_DIR: core

build:user:
  extends: .build_java_gradle
  dependencies: []
  variables:
    PROJECT_DIR: java/users

test:core:
  extends: .test_java_gradle_with_testcontainers
  dependencies:
    - build:core
  variables:
    PROJECT_DIR: core

test:user:
  extends: .test_java_gradle
  dependencies:
    - build:user
  variables:
    PROJECT_DIR: java/users
