# Конфигурация CI/CD для репозиториев микросервисов проекта "Цифровой след".
# Специфичные настройки под конкретный микросервис вынесены в раздел "variables".

include:
  - 'gitlab-ci-templates/.java-ci.yml'

variables:
  STAGING_FOLDER: /opt/hubabank
  CORE_PROJECT_DIR: core
  USER_PROJECT_DIR: java/users

stages:
  - build
  - test

sample:
  image: gradle:jdk17-alpine
  stage: build
  tags:
    - docker
  script:
    - echo $PROJECT_DIR
  variables:
    PROJECT_DIR: $CORE_PROJECT_DIR

build:core:
  extends: .build_java_gradle
  variables:
    PROJECT_DIR: $CORE_PROJECT_DIR

build:user:
  extends: .build_java_gradle
  variables:
    PROJECT_DIR: $USER_PROJECT_DIR

test:core:
  extends: .test_java_gradle_with_testcontainers
  needs:
    - build:core
  variables:
    PROJECT_DIR: $CORE_PROJECT_DIR

test:user:
  extends: .test_java_gradle
  needs:
    - build:user
  variables:
    PROJECT_DIR: $USER_PROJECT_DIR
