# Конфигурация CI/CD для репозиториев микросервисов проекта "Цифровой след".
# Специфичные настройки под конкретный микросервис вынесены в раздел "variables".

include:
  - 'gitlab-ci-templates/.template.yml'

variables:
  STAGING_FOLDER: /opt/hubabank

stages:
  - build
  - test

build:core:
  extends: .build_java

test:core:
  image: gradle:jdk17-alpine
  stage: test
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - 'core/*'
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:dind
      # Явное отключение tls, чтобы избежать прерывания запуска docker'а
      command: ["--tls=false"]
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle_home
  script:
    - cd core
    - gradle test
  cache:
    - key: dependencies-cache
      paths:
        - .gradle_home
  artifacts:
    when: always
    reports:
      junit: core/build/test-results/test/**/TEST-*.xml
