version: '3.3'

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: BFF-client.Api\Dockerfile
    ports:
      - "1000:8080"
    environment:
      ConnectionStrings__DefaultConnection: Server=database;Port=5432;Database=gateway_client_service;Username=postgres;Password=${DATABASE_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Staging
    depends_on:
      - local-database
    networks:
      - db-network
    restart: always

  local-database:
    image: postgres:latest
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gateway_client_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - db-network

networks:
  db-network:
    driver: bridge