.deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH
    #== $CI_DEFAULT_BRANCH
      when: manual
  script:
    - rm -rf $WORKING_DIR
    - cp -r .infra/deploy/$ENVIRONMENT $WORKING_DIR
    - cd $WORKING_DIR
    - cp $ENV .env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker compose up -d