.deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH
    #== $CI_DEFAULT_BRANCH
      when: manual
  script:
    - sudo rm -rf $WORKING_DIR
    - sudo cp -r .infra/deploy/$ENVIRONMENT $WORKING_DIR
    - cd $WORKING_DIR
    - echo $ENV
    - echo $WORKING_DIR
    - sudo cp $ENV .env
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sudo docker compose up -d