.build_docker_image:
  image: docker:25
  stage: image
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - $PROJECT_DIR/**/*
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_ARGS: ""
  services:
    - name: docker:25-dind
      # Явное отключение tls, чтобы избежать прерывания запуска docker'а
      command: ["--tls=false"]
  script:
    - cp $DOCKERFILE $PROJECT_DIR
    - cd $PROJECT_DIR
    - echo "$DOCKER_ARGS"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build $DOCKER_ARGS -t $CI_REGISTRY/hits-tsu/huba/$IMAGE:latest .
    - docker push $CI_REGISTRY/hits-tsu/huba/$IMAGE:latest