xcassets:
  inputs:
    - ../../../Resources/Assets/
  outputs:
    - templatePath: Templates/assets
      output: ../Generations/AppAssets+Generated.swift
      params:
        forceFileNameEnum: true

fonts:
  inputs:
    - ../../../Resources/Fonts/
  outputs:
    - templatePath: Templates/fonts
      output: ../Generations/AppFonts+Generated.swift
      params:
        enumName: AppFonts
