version: '3.8'
services:
  database:
    image: 'postgres:16.1-alpine3.19'
    ports:
      - '1234:5432'
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
      POSTGRES_DB: core
  wiremock:
    image: 'wiremock/wiremock:3.4.2-alpine'
    ports:
      - '8081:8080'
    volumes:
      - './src/test/resources/wiremock/__files:/home/wiremock/__files'
      - './src/test/resources/wiremock/mappings:/home/wiremock/mappings'

