version: '3.8'
services:

  gateway-client:
    image: registry.gitlab.com/hits-tsu/huba/gateway-client:latest
    container_name: hits-huba-gateway-client
    ports:
      - "9001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    volumes:
      - ./gateway-client/appsettings.Staging.json:/app/appsettings.Staging.json:ro
    networks:
      - 'hits-huba-network'

  gateway-employer:
    image: registry.gitlab.com/hits-tsu/huba/gateway-employer:latest
    container_name: hits-huba-gateway-employer
    ports:
      - "9002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    volumes:
      - ./gateway-employer/appsettings.Staging.json:/app/appsettings.Staging.json:ro
    networks:
      - 'hits-huba-network'

  core:
    image: registry.gitlab.com/hits-tsu/huba/core:latest
    container_name: hits-huba-core
    ports:
      - "9004:8080"
    environment:
      POSTGRES_HOST: hits-huba-database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: core_service
      USERS_SERVICE_URL: http://hits-huba-users:8080/users/api/v1/
    networks:
      - 'hits-huba-network'

  users:
    image: registry.gitlab.com/hits-tsu/huba/users:latest
    container_name: hits-huba-users
    ports:
      - "9003:8080"
    environment:
      POSTGRES_HOST: hits-huba-database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
      POSTGRES_SCHEMA: users_service
    networks:
      - 'hits-huba-network'

  database:
    image: postgres:16.1-alpine3.19
    container_name: hits-huba-database
    ports:
      - '9000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - 'hits-huba-network'

  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: huba
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: huba

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbitmq-haproxy:
    image: haproxy:1.7
    container_name: hits-huba-rabbitmq
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - 'hits-huba-network'

networks:
  hits-huba-network: