@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Пользователь" as User
participant "Мобильное приложение" as MobileApp
participant "Сервис кабинета сотрудника" as EmployerService
participant "Сервис ядро" as CoreService
participant "Сервис кредитов" as LoanService

User -> MobileApp
activate MobileApp

    MobileApp -> EmployerService
    activate EmployerService

        note right EmployerService
        Прокидываем Bearer токен в header Authorization
        end note

        EmployerService -> LoanService: POST /users/{id}/loans
        activate LoanService
        return HTTP 200
    return HTTP 200
return Экран со списком кредитов

@enduml