@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Пользователь" as User
participant "Мобильное приложение" as MobileApp
participant "Сервис кабинета сотрудника" as EmployerService
participant "Сервис ядро" as CoreService

User -> MobileApp
activate MobileApp

    MobileApp -> EmployerService
    activate EmployerService

        EmployerService -> CoreService: GET /users/{id}/bills/{billId}/transactions
        activate CoreService
        return HTTP 200
    return HTTP 200
return Экран с историей

@enduml