version: '3.5'
services:
  pg_db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment: 
      POSTGRES_PASSWORD: root
    shm_size: '1gb'
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"

volumes:
  db_data:
    driver: local
    