version: '3.3'

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: BFF-client.Api\Dockerfile
    ports:
      - "1000:8080"
    environment:
      ConnectionStrings__Postgres: Server=database;Port=5432;Database=credit_db;Username=postgres;Password=${DATABASE_PASSWORD};Application Name=credit;Pooling=true;Maximum Pool Size=4;Connection idle Lifetime=60;Max Auto Prepare=1000
      ConnectionStrings__Hangfire: Server=database;Port=5432;Database=credit_db;Username=postgres;Password=${DATABASE_PASSWORD};Application Name=credit;Pooling=true;Maximum Pool Size=4;Connection idle Lifetime=60;Max Auto Prepare=1000
      ASPNETCORE_ENVIRONMENT: Staging
      RABBITMQ_HOST: 194.147.90.192
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: huba
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: huba
    depends_on:
      - local-database
    networks:
      - db-network
    restart: always

  local-database:
    image: postgres:latest
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: credit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - db-network

networks:
  db-network:
    driver: bridge