.build_java:
  image: gradle:jdk17-alpine
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - '$PROJECT_DIR/*'
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle_home
  script:
    - cd $PROJECT_DIR
    - gradle clean build -x test
  cache:
    - key: dependencies-cache
      paths:
        - .gradle_home
  artifacts:
    paths:
      - $PROJECT_DIR/build/libs/*.jar
    expire_in: 1 week